### ISSUE TITLE
Bug when running the Readme `Usage` 

### ISSUE THREAD

**Issue by Nkarnaud** [terminusdb/terminusdb-client-python#207]
When running the usage in the readme am having issues with context

**To Reproduce**
1- Install the python client 
2- Connect to the terminusdb
3-  Create a database
4-  Error occurs when creating the db schema

**Expected behavior**
Expecting to have a newly created schema

**Error logs**
.`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nkeumo/Documents/pycharmWorkspace/terminusdb-client-python/terminusdb_client/woqlquery/woql_query.py", line 481, in execute
    return client.query(self, commit_msg, file_dict=file_dict)
  File "/Users/nkeumo/Documents/pycharmWorkspace/terminusdb-client-python/terminusdb_client/woqlclient/woqlClient.py", line 1101, in query
    request_woql_query["@context"] = self._context
AttributeError: 'WOQLClient' object has no attribute '_context'`
 
This occurs when I run this command ` WOQLQuery().doctype("scm:student").property("scm:name", "xsd:string").execute(client, "student schema created.")`

**System information (please complete the following information):**
 - OS: [e.g. Mac OS Bigsur]
 -  terminus-client-python dev version

**Comment by Marufenko** [comment]
Hi @Nkarnaud, I can add that it's not reproducible under README instruction as it contains step to create db `client.create_database()` under which `self._context` is defined. The issue you mentioned is reproduced when a new client is initialized and connected to the existing db (without creating one), then the `self._context` attribute is not defined.

**Comment by Cheukting** [comment]
Hi @Nkarnaud and @Marufenko thanks for pointing it out. From the look of it, the problem is when there's not a database connected (either by specifying it in `connect`, `create_database` or `set_db`). To make it better, it should point out the problem (not connected to a database) instead of the error that it is raising now. Feel free to send a PR to fix it if you want otherwise I will patch it before the next release :-)

**Comment by Marufenko** [comment]
Hi, I will open PR

**Comment by Cheukting** [comment]
@Marufenko in the case when a database already exists, it will cause an error because you cannot create a database with the same id if it already exists. I would recommend raising a ProgrammingError saying "database already exist" if it already existed. You can use `list_databases` to get a list of databases that exist.

**Comment by Marufenko** [comment]
@Cheukting that's already in place, here's behavior of the current master
```
>>> from terminusdb_client import WOQLQuery, WOQLClient
>>> client = WOQLClient(server_url = "https://127.0.0.1:6363")
>>> client.connect(key="root", account="admin", user="admin")
>>> client.create_database("university", accountid="admin", label="University Graph", description="graph connect")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmarufenko/PycharmProjects/terminusdb-client-python/terminusdb_client/woqlclient/woqlClient.py", line 727, in create_database
    self._dispatch("post", self._db_url(), details)
  File "/Users/mmarufenko/PycharmProjects/terminusdb-client-python/terminusdb_client/woqlclient/woqlClient.py", line 1653, in _dispatch
    raise DatabaseError(request_response)
terminusdb_client.errors.DatabaseError: Database already exists.
```

what was reported by @Nkarnaud is if you just follow the next step from the example in the readme (after you got the error above that db already exists) you end up with the following error
```
>>> WOQLQuery().doctype("scm:student").property("scm:name", "xsd:string").execute(client, "student schema created.")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmarufenko/PycharmProjects/terminusdb-client-python/terminusdb_client/woqlquery/woql_query.py", line 453, in execute
    return client.query(self, commit_msg, file_dict=file_dict)
  File "/Users/mmarufenko/PycharmProjects/terminusdb-client-python/terminusdb_client/woqlclient/woqlClient.py", line 1079, in query
    request_woql_query["@context"] = self._context
AttributeError: 'WOQLClient' object has no attribute '_context'
```

the root cause: `self._db` is assigned before db creation attempt and `self._context` after, so it's not reachable at all if creation attempt returns an error, it's here:
```
    def create_database(
        ...
        self._db = dbid
        self._dispatch("post", self._db_url(), details)
        self._context = self._get_prefixes()
```

What is proposed in the PR is to move `self._context` under `finally` statement so it's to be assigned regardless is db created or already exists.
Another way I see is to refactor `def create_database()` so `self._db` and `self._context` to not be assigned on db creation attempt, which would require to call `set_db()` regardless of the outcome of creation attempt.

**Comment by Cheukting** [comment]
I think this may not be relevant anymore when the document API interface is fully inaction, we will disable the _context if that make sense. Let's review it when the next version is released.

**Comment by Cheukting** [comment]
I think this will not be relevant after the new release.
