### ISSUE TITLE
Delete Document and other APIs should take iterables of documents as that is what the interface returns

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb-client-python#238]
If you set up a `client.get_documents_by_type()` and subsequently feed the iterable to `client.delete_document()`, it throws an error. This is because we return iterables, but do not consume them. Consistency here would be good!

**Comment by Cheukting** [comment]
As inputting an iterable is really not doing much to improve what delete_documents could do (it will still collect all the elements before making the API call) I would suggest the other way round: adding as_list option for get_document_by_type which will return a list instead of iterable. I can also make the conversion to convert an iterable to a list is delete_documents as well but I would suggest just passing elements as a list in this case. In stort, I will 1) add the as_list option to get_documents_by_type and 2) allow delete_docuemnt to accept iterables but the cannon is to use method 1, pass everything as list
